### ISSUE TITLE
Send a report to client

### ISSUE THREAD

**Issue by bl96** [TIS2019-FMFI/aurelium#2]
Send a report from our first meeting to ing. Varga.

**Comment by pavelpetrovic** [comment]
nothing important, just a side comment: submitter would be somebody who submits something to some institution, body, etc. For instance someone who submits a proposal for building a dam submits his case to a local government, he or she would be a submitter. In your case, you are talking about your client, customer, perhaps end-user or partner. :)

**Comment by bl96** [comment]
Update: changed tittle.

**Comment by pavelpetrovic** [comment]
Matejovu tasku davam na vratnicu.
