### ISSUE TITLE
Design (Diagrams)

### ISSUE THREAD

**Issue by bl96** [TIS2019-FMFI/aurelium#21]
* [ ] UML component diagram  Miro
* [ ]  UML class diagram Ivana
* [x]  UML use-case diagram Vsetci
* [x]  UML state/UML sequence diagram Martina
* [x]  návrh používateľského rozhrania
* [x]  podrobná špecifikácia vonkajších interfejsov --> s tym rozhranim co komunikuje to popiseme (popis ako budeme vytahovat z kamery obrazky, taka a taka kniznica, vytiahnutie framu v xy formate)  Matej
* [x]  podrobný dátový model formátov súborov   Matej

**Comment by martinavesela** [comment]
![Use-case-diagram-Aurelium](https://user-images.githubusercontent.com/47821741/68478693-cb41e300-0230-11ea-83a5-41f5c7fa644d.png)

**Comment by martinavesela** [comment]
https://docs.google.com/document/d/1bXso8yO7L-M4jFYgBNgWwpr7PHN1ArOGuQ2OlY6R8Wk/edit?usp=sharing

**Comment by martinavesela** [comment]
![Aurelium_State_Diagram](https://user-images.githubusercontent.com/47821741/68606715-4d3f3f80-04af-11ea-951a-5b73549cdf43.png)

**Comment by martinavesela** [comment]
![aurelium_composite](https://user-images.githubusercontent.com/47821741/68789727-4dbe0e80-0646-11ea-8694-7bfd40df0450.png)

**Comment by bl96** [comment]
[interface-specific-1.pdf](https://github.com/TIS2019-FMFI/aurelium/files/3845245/interface-specific-1.pdf)

**Comment by pavelpetrovic** [comment]
- ak sa bude vykreslovat ramcek okolo tvare, tak aj komponent na detekciu potrebuje interface na ui komponent
- bolo by pekne, keby interfejsy mali aj mena... ale prezijem to. mozete upravit, ak budete mat moznost.
inak fajn

**Comment by martinavesela** [comment]
![Aurelium_Composite_Diagram](https://user-images.githubusercontent.com/47821741/69143005-483e4980-0ac8-11ea-9fd1-86feefefadf9.png)

**Comment by martinavesela** [comment]
![Aurelium_Class_Diagram](https://user-images.githubusercontent.com/47821741/69143012-4c6a6700-0ac8-11ea-8d77-b4bce24baede.png)

**Comment by martinavesela** [comment]
![aurelium_class_diagram](https://user-images.githubusercontent.com/47821741/69829010-8f41e280-121e-11ea-8098-f4f5f53e205b.png)

**Comment by pavelpetrovic** [comment]
dakujem, neviem ako to myslite.
nie je to v sulade s tym, o com sme sa rozpravali na stretnuti, co nemusi znamenat, ze to nemoze byt takto, ale takto z obrazku nemam predstavu ako to myslite.

na stretnuti sme sa rozpravali o tom, ze tie jednotlive podtriedy triedy detector budu jednotlive druhy detektorov,
napr.

EyeDetector
FaceDetector
MouthDetector

ale kedze FaceDetector nedetekuje ukony, ale ramcek, tak aj navratova hodnota vsetkych tych metod detect()
by mohla byt nie string ale nejaky DetectionResult, ktory je len abstraktnou triedou a ma dve podtriedy:
ActResult  (s jednym atributom actName:string)
FrameResult (s atributom frame:Frame, tu triedu tam tiez uz nevidim (definuje parametre ramceka - x,y,w,h))

GestureDetector by mohol mat atribut currentGesture - v ktorom sa postupne vytvara gesto, ktore pouzivatel vytvara

atributom direction, is_closed, smile, tongue nerozumiem, lebo to bude zakodovane uz priamo v tom stringu,
ostatne veci su private pre dany detektor a netreba ich do diagramu davat.

naopak trieda GestureDetection by mohla mat metodu readSettings(), ktora nacita konfiguracny subor
a povytvara instancie triedy Gesture a tiez atribut maxActTime (tiez nacitany z konfigu), s casom, ktory
ukoncuje gesto, ak pocas neho nepride dalsi ukon.

tiez by mohol mat atribut detectionState, ktory by mohol byt nejakeho enum typu, pricom stavy, ak si dobre
spominam sme zatial nasli tieto:

enum DetectionState
{
  waitingForGesture,
  gestureBeingPerformed,
  gestureResultShown,
  sleeping
}

v triede Display sa mi nepaci, ze metodky zacinaju "print_", ked nic netlacia, ale zobrazuju,
takze skor by to mohlo byt "show_" a namiesto toho "show_", co uz mate, by mohlo byt
trebars "display_"

v triede GestureDetection by som ocakaval nejaku metodku main(), ktora bude hlavne vlakno programu, v ktorom to cele stale bezi.

skoda, ze system neprodukuje ziadne logy o tom, ako je vyuzivany - kolko akych gest bolo detekovanych, to moze byt
zaujimave len na pozretie raz za cas (hoci v nejakom textovom subore), aby sa management muzea mohol pozriet, ako
je exponat vyuzivany.  taketo veci nad ramec KP, ktore nijak nenarusaju funkcionalitu opisanu v KP moze pridat aj bez toho,
aby ste to uvadzali v KP a vo vyslednej tech. dokumentacii sa o tom zmienit (v casti "Navod na pouzivanie").

kedze v KP mate aj ten screen saver, tak by tam mohla byt v tom GuestureDetection aj metodka wakeUpScreenSaver()
(alebo nieco podobne), ktora sa bude volat, vzdy ked system detekuje nejaku tvar a sposobi zobudenie screen savera,
ak nahodou bol aktivovany - v navrhu by mala byt navrhunuta aj funkcionalita, ktora je optional, ci sa nakoniec implementuje,
je druha vec, ale v navrhu by to byt malo.
(cize aj technologia, ktora dokaze pocitac zobudit zo screen savera by mala byt opisana v prvej casti navrhu - o externych
interfejsoch).
