### ISSUE TITLE
Upravit katalog poziadaviek

### ISSUE THREAD

**Issue by bl96** [TIS2019-FMFI/aurelium#29]
* [ ] rozdelit zlozenu poziadavku
* [ ] doplnit poziadavku s low light svetlom

**Comment by pavelpetrovic** [comment]
tiez upozornujem na nekonzistentnost KP s Vasou predstavou, ktoru ste mi dnes prezentovali, konkretne 

3.1.8 "...mena súboru s obrázkom, ktorý sa má zobraziť po jeho detekcii."

uvedomte si, ze tento KP ste uz dali schvalit zadavatelovi. Preto, ak chcete urobit nieco ine, ako tam je napisane, tak to treba este v KP zmenit a znovu si vyziadat schvalenie s tym, ze jasne cervenou vyznacite vsetky veci, ktore ste v KP od schvalenia zmenili a ospravedlnite sa mu za to, ze robite zmatky.

normalne byva, ze zmeny prichadzaju od zadavatela a nie od vyvojoveho timu. :)

tychto nezrovnalosti medzi KP a Vasou predstavou moze byt viac, takze to dokladne vsetko skontrolujte.
